version: '3.5'
services:
  etcd:
    build:
      context: ./milvus_containers/etcd_continer
    container_name: milvus_etcd_container
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/etcd:/etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - database_network
      - shared_network

  minio:
    build:
      context: ./milvus_containers/minio_continer
    container_name: milvus_minio_container
    ports:
      - "9001:9001"
      - "9000:9000"
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/minio:/minio_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - database_network
      - shared_network

  standalone:
    build:
      context: ./milvus_containers/standalone_continer
    container_name: milvus_standalone_container
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/milvus:/var/lib/milvus
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    ports:
      - "19530:19530"
      - "9091:9091"
      - "2379:2379"
      - "2222:2222"
      - "80:80"
      - "443:443"
    depends_on:
      - "etcd"
      - "minio"
    networks:
      - database_network
      - shared_network

  attu:
    build:
      context: ./milvus_containers/attu_continer
    container_name: milvus_attu_container
    environment:
      - MILVUS_URL=http://standalone:19530
      - HOST_URL=http://host.docker.internal:8000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8000:3000"
    working_dir: /app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 20s
      retries: 3
    depends_on:
      - "standalone"
    networks:
      - database_network
      - shared_network

networks:
  database_network:
    driver: bridge
  shared_network:
    driver: bridge

# docker-compose -f docker-compose.yml up -d